### ISSUE TITLE
Does not work on Node > 5 (Unstable)

### ISSUE THREAD

**Issue by d2fong** [cytoscape/slush-cytoscape-extension#10]
Here is what I do:
```sh
npm install -g slush
npm install -g slush-cytoscape-extension
slush cytoscape-extension
```

And I get the following:
```sh
(node:58141) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[slush] No generator by name: "cytoscape-extension" was found!
[slush] Try installing it with `npm install -g slush-cytoscape-extension` first.
```

Furthermore, when installing slush-cytoscape-extension, I get the following related message:
```sh
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

Throws an error related to deprecated packages incompatible with node versions >= 7 (but it still doesn't work for node 6.

Versions I tried:
* 7.7.1
* 6.11.0

Versions that seem to work:
* 5.12.0

**Comment by d2fong** [comment]
Seems to work now with Node 7.7.1, but I am unsure why...

**Comment by maxkfranz** [comment]
Wasn't following the repo, so I missed this.

Anyway, it should work in `node@6`.  That's what I'm using.  It gives warnings about graceful-fs in 6, but it should still work.  There are no guarantees it will work in 7, though.

In order to fix this, we need to upgrade to `gulp@4`.  Currently, it's not released yet:

- Source : https://github.com/gulpjs/gulp/tree/4.0
- Issues
    - https://github.com/gulpjs/gulp/issues/1486
    - https://github.com/gulpjs/gulp/issues/1945

**Comment by maxkfranz** [comment]
Instead of `npm install -g slush-cytoscape-extension` you need `cd slush-cytoscape-extension && npm link`

You need to do `npm remove -g slush-cytoscape-extension` first to get rid of the remote install.

**Comment by maxkfranz** [comment]
@d2fong I've updated unstable with improvements:

- Test support
- File separation (core, collection, layout)
- Discrete layout class
- Continuous (impl) layout class
- Continuous base class to pull out common/general force-directed layout operations and make the continuous impl class terser
- Tested on node@6

Let me know if it works for you, and we can then push an update to npm.

**Comment by d2fong** [comment]
Okay I will test it out

**Comment by d2fong** [comment]
@maxkfranz I have been playing around with these new changes and they seem to work fine for me.  I haven't been noticing any problems so I think it should be fine to push an update.

**Comment by d2fong** [comment]
@maxkfranz oh I actually do run into 1 minor issue.

I get 
```js
cytoscape.min.js:63 The style property `curve-style: bezer` is invalid
```
When I load the demo.
