### ISSUE TITLE
Discrete layout class template file throws TypeError

### ISSUE THREAD

**Issue by d2fong** [cytoscape/slush-cytoscape-extension#12]
Using cytoscape 3.1.4

When creating a new layout extension, I get the following error once I register the layout and try to run it.
```js
Uncaught TypeError: Class constructor Layout cannot be invoked without 'new'
    at o (cytoscape.min.js:39)
    at u.layout (cytoscape.min.js:32)
    at u.layout (cytoscape.min.js:27)
    at a.<anonymous> (demo.html:108)
    at e (lodash.min.js:68)
    at o (lodash.min.js:68)
    at i (lodash.min.js:68)
o @ cytoscape.min.js:39
layout @ cytoscape.min.js:32
layout @ cytoscape.min.js:27
(anonymous) @ demo.html:108
e @ lodash.min.js:68
o @ lodash.min.js:68
i @ lodash.min.js:68
```

**Comment by maxkfranz** [comment]
@d2fong Does 872ea70 help?  It should work around the issue by having Babel convert `class` to `function`, but we should probably address this in the core lib as well.

**Comment by d2fong** [comment]
@maxkfranz it doesn't throw an error anymore once I add .babelrc but I don't think it is working properly.  The layout doesn't seem to run when I call it.

**Comment by maxkfranz** [comment]
Saving the default options is missing from the scaffolder: https://github.com/cytoscape/slush-cytoscape-extension/blob/master/templates/src/layout/discrete.js#L26
