### ISSUE TITLE
Cytoscape.min.js not found in demo.html

### ISSUE THREAD

**Issue by kinimesi** [cytoscape/slush-cytoscape-extension#9]
@maxkfranz I think you removed `cytoscape.min.js` from [http://cytoscape.github.io/cytoscape.js/api/cytoscape.js-latest/cytoscape.min.js](http://cytoscape.github.io/cytoscape.js/api/cytoscape.js-latest/cytoscape.min.js) but did not update the extension.

**Comment by maxkfranz** [comment]
Yes, most of the extensions need to be updated.  It's just been low relative priority, as I have other projects to work on.  There are also structural changes coming to the extension scaffolder, but I haven't had time to test it and push it.  Those changes will probably come together.

**Comment by maxkfranz** [comment]
Resolved in the unstable branch that we're working on for the next release.

Using https://unpkg.com/cytoscape/dist/cytoscape.min.js
